import { defineStore } from "pinia";
import { ref } from "vue";

export const useData = defineStore("employeeData", () => {
  const datas = ref([
    {
      id: 1,
      photo: "../user/1.jpeg",
      name: "Ye Min Htun",
      location: "Yangon office",
      email: "yeminhtun@better.hr",
      phone: "+959483482381",
      department: "Product dpt",
      tag: "Intern",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 2,
      photo: "../user/2.jpeg",
      name: "Kyi Sin Hsu Thar",
      location: "Yangon office",
      email: "Kyisinhsuthar@better.hr",
      phone: "+959483482381",
      department: "Product dpt",
      tag: "Trainee",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 3,
      photo: "../user/3.jpeg",
      name: "Myat The Chit",
      location: "Yangon office Sue lay",
      email: "myatthechit@better.hr",
      phone: "+94123456789",
      department: "Development",
      tag: "Spannish-spoken",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 4,
      photo: "../user/4.jpeg",
      name: "Walter",
      location: "Mandalay office",
      email: "zayerlinhtun@better.hr",
      phone: "+959483482381",
      department: "Tech & Development",
      tag: "Intern",
      manager: "Zayer Zay",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "COO"
    },
    {
      id: 5,
      photo: "../user/5.jpeg",
      name: "Johnathan",
      location: "Yangon office",
      email: "yeminhtun@better.hr",
      phone: "+959483482381",
      department: "Product dpt",
      tag: "Intern",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 6,
      photo: "../user/6.jpeg",
      name: "Devi",
      location: "Yangon office",
      email: "Kyisinhsuthar@better.hr",
      phone: "+959483482381",
      department: "Customer success",
      tag: "Trainee",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 7,
      photo: "../user/7.jpeg",
      name: "Mike",
      location: "Yangon office Sue lay",
      email: "myatthechit@better.hr",
      phone: "+94123456789",
      department: "Customer success",
      tag: "Spannish-spoken",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 8,
      photo: "../user/8.jpeg",
      name: "Biden",
      location: "Mandalay office",
      email: "zayerlinhtun@better.hr",
      phone: "+959483482381",
      department: "Tech & Development",
      tag: "Intern",
      manager: "Zayer Zay",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "COO"
    },
    {
      id: 9,
      photo: "../user/9.jpeg",
      name: "Eric",
      location: "Yangon office",
      email: "yeminhtun@better.hr",
      phone: "+959483482381",
      department: "Product dpt",
      tag: "Intern",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 10,
      photo: "../user/10.jpeg",
      name: "Elanor",
      location: "Yangon office",
      email: "Kyisinhsuthar@better.hr",
      phone: "+959483482381",
      department: "Customer success",
      tag: "Trainee",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 11,
      photo: "../user/11.jpeg",
      name: "Wilson",
      location: "Yangon office Sue lay",
      email: "myatthechit@better.hr",
      phone: "+94123456789",
      department: "Customer success",
      tag: "Spannish-spoken",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    },
    {
      id: 12,
      photo: "../user/12.jpeg",
      name: "Luke",
      location: "Mandalay office",
      email: "zayerlinhtun@better.hr",
      phone: "+959483482381",
      department: "Tech & Development",
      tag: "Intern",
      manager: "Zayer Zay",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "COO"
    },
    {
      id: 13,
      photo: "../user/11.jpeg",
      name: "Wilson",
      location: "Yangon office Sue lay",
      email: "myatthechit@better.hr",
      phone: "+94123456789",
      department: "Customer success",
      tag: "Spannish-spoken",
      manager: "Myo Zaw Hein",
      employeeCode: "004-342",
      positions: "UX Designer",
      nrc: "12/PaBaTa(N)00700",
      date: "12.2.2021",
      terminate: "-",
      managerPosition: "CEO"
    }
  ]);
  return { datas };
});
